## https://opentelemetry.io/docs/collector/configuration
##

# https://opentelemetry.io/docs/collector/components/receiver
receivers:

  # Log Files
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver

  # Forward Protocol
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/fluentforwardreceiver
  fluentforward:
    endpoint: 0.0.0.0:8006

  # Prometheus Scrape Configs (self-scraping)
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
  prometheus:
    config:
      scrape_configs:
        - job_name: opentelemetry-collector
          scrape_interval: 10s
          static_configs:
            - targets: [localhost:8888]

  # Prometheus Remote Write
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusremotewritereceiver
  prometheus_remote_write:
    endpoint: 0.0.0.0:9090

  # OpenTelemetry Protocol (OTLP)
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

# https://opentelemetry.io/docs/collector/components/processor
processors:

  # Bounding memory usage to prevent OOM crashes.
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80        # Max memory usage as a percent of total available (e.g., 80% of 1GB = 800MB)
    spike_limit_percentage: 20  # Max allowed usage spike between checks (e.g., 20% of 800MB = 160MB)

  # Add host info to logs, metrics, and traces.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]
    timeout: 5s
    override: false

  # Modify attributes of logs, metrics, and traces.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
  resource:
    attributes:
      - key: collector
        value: otel
        action: insert

  # Transform logs, metrics, and traces using custom statements.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["message"], attributes["msg"])
          - delete_key(attributes, "msg")

  # Filter out health check and metrics requests.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
  filter:
    error_mode: ignore
    log_conditions:
      - conditions:
        # If any condition is met, the telemetry is dropped.
        - IsMatch(log.attributes["req_path"], "^/health.*")
        - IsMatch(log.attributes["req_path"], "^/metrics.*")

  # Batch logs, metrics, and traces for performance improvements.
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
  batch:
    timeout: 5s
    send_batch_size: 4096
    send_batch_max_size: 0  # No max batch size limit

# https://opentelemetry.io/docs/collector/components/exporter
exporters:

  # Standard Output
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter
  debug:
    verbosity: normal  # Change to `detailed` for full payload dumps
    sampling_initial: 2
    sampling_thereafter: 10

  # Files
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter
  file/logs:
    path: /data/logs.json
    format: json
    flush_interval: 5s
    rotation:
      max_megabytes: 100  # The maximum size of a log file before it gets rotated.
      max_days: 7         # The maximum number of days to retain old log files.
      max_backups: 3      # The maximum number of backup log files to keep.
      localtime: false    # Use local time for log file timestamps.

  # Prometheus metrics for scraping
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: opentelemetry_collector
    const_labels:
      collector: opentelemetry-collector

  # Push metrics to Prometheus/Mimir
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter

  # Forward data to an upstream collector via OpenTelemetry Protocol (HTTP)
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter

  # Forward data to an upstream collector via OpenTelemetry Protocol (gRPC)
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter

# https://opentelemetry.io/docs/collector/components/extension
extensions:

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health
    response_body:
      healthy: OK
      unhealthy: FAIL

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
  pprof:
    endpoint: 0.0.0.0:1777

  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]

  # https://opentelemetry.io/docs/collector/internal-telemetry
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

  pipelines:
    logs:
      receivers:  [fluentforward]
      processors: [memory_limiter, resourcedetection, resource, transform, filter, batch]
      exporters:  [debug, file/logs]
    metrics:
      receivers:  [prometheus, prometheus_remote_write]
      processors: [memory_limiter, resourcedetection, resource, transform, filter, batch]
      exporters:  [prometheus]
    traces:
      receivers:  [otlp]
      processors: [memory_limiter, resourcedetection, resource, transform, filter, batch]
      exporters:  [debug]
